"""empty message

Revision ID: 822937ba7e67
Revises: fbcdae73e41a
Create Date: 2021-01-31 19:45:40.774424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822937ba7e67'
down_revision = 'fbcdae73e41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')

    op.alter_column('todolists', 'completed', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
